=== pegahsafaie/GraphGenerator/src/main/resources/profile_groundTruth_schema.json
{
   "$id": "http://example.com/example.json", 
   "$schema": "http://json-schema.org/draft-06/schema#", 
   "definitions": {}, 
   "items": {
     "$id": "/items", 
     "properties": {
        "adj": {
          "$id": "/items/properties/adj", 
         "items": {
           "$id": "/items/properties/adj/items", 
           "title": "The 0 Schema.", 
           "type": "string"
         }, 
         "type": "array"
       }, 
       "location": {
         "$id": "/items/properties/location", 
         "items": {
           "$id": "/items/properties/location/items", 
           "title": "The 0 Schema.", 
           "type": "string"
         }, 
         "type": "array"
       }, 
       "name": {
         "$id": "/items/properties/name", 
         "title": "The Name Schema.", 
         "type": "string"
       }, 
       "personality": {
         "$id": "/items/properties/personality", 
         "title": "The Personality Schema.", 
         "type": "string"
       }, 
       "sentiment": {
         "$id": "/items/properties/sentiment", 
         "title": "The Sentiment Schema.", 
         "type": "string"
       }, 
       "verb": {
         "$id": "/items/properties/verb", 
         "items": {
           "$id": "/items/properties/verb/items", 
           "title": "The 0 Schema.", 
           "type": "string"
         }, 
         "type": "array"
       }
     }, 
     "type": "object"
   }, 
   "type": "array"
 }

=== pegahsafaie/GraphGenerator/src/main/webapp/ground/ground_profiles_SampleArticle.json
[
  {
    "name": "Mahmoud Ahmadinejad",
    "adj": [
      "Iranian President",
      "incumbent President",
      "Tehran Mayor"
    ],
    "verb": [
      "win",
      "claim",
      "call",
      "focus",
      "begin",
      "respond"
    ],
    "location": [
      "Iran",
      "Tehran"
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Mir-Hossein Mousavi",
    "adj": [
      "opposition candidates"
    ],
    "verb": [
      "claime",
      "lodge",
      "announced",
      "visit",
      "lodge"
    ],
    "location": [
      "Iran"
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Mehdi Karroubi",
    "adj": [
      "opposition candidates",
      "Former chairman of Iranian parliament"
    ],
    "verb": [
      "claim",
      "state",
      "ask",
      "call",
      "visit"
    ],
    "location": [
      "Iran"
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Rezaee",
    "adj": [
	"opossittion candidates"
    ],
    "verb": [
      "lodging",
      "lodge"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Ayatollah Ali Khamenei",
    "adj": [
      "Supreme Leader",
      "Ayatollah"
    ],
    "verb": [
      "order",
      "claimed",
      "escaped",
      "will",
      "speak"
    ],
    "location": [
      "Iran",
      "Tehran"
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Basij",
    "adj": [
      "paramilitary",
      "auxiliary wing"
    ],
    "verb": [
      "suppressed",
      "attacked",
      "destroy"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Neda Agha-Soltan",
    "adj": [
      "victim",
      "young Iranian woman"
    ],
    "verb": [
      "die"
    ],
    "location": [
      "Tehran"
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Ayatollah Khomeini",
    "adj": [
      "successor"
    ],
    "verb": [
      "claimed",
      "declared",
      "ordered"
    ],
    "location": [
      "Iran",
      "Iraq"
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Mojahedin Khalq",
    "adj": [
      "Marxist-Islamist"
    ],
    "verb": [
      "oppose"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Mohammad Khatami",
    "adj": [
      "little-known reformist cleric",
      "president"
    ],
    "verb": [
      ""
    ],
    "location": [
      "Iran"
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Rafsanjani",
    "adj": [
      "reformist"
    ],
    "verb": [
      "fail"
    ],
    "location": [
      "Iran",
      "Tehran"
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Saeed Hajjarian",
    "adj": [
      "main theorist behind the movement",
      "former presidential advisor"
    ],
    "verb": [
      "arrest"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Behzad Nabavi",
    "adj": [
      "MIRO founder"
    ],
    "verb": [
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Mohsen Mirdamadi",
    "adj": [
      "IIPF leader"
    ],
    "verb": [
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Ahmad-Reza Radan",
    "adj": [
      "Police Chief"
    ],
    "verb": [
      "stated"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Gholam Hossein Mohseni-Ejehei",
    "adj": [
      "Intelligence minister"
    ],
    "verb": [
      "linked"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Abdolfattah Soltani",
    "adj": [
      "Human rights lawyer"
    ],
    "verb": [
      "arrest",
      "say"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Mohammadreza Habibi",
    "adj": [
      "prosecutor-general"
    ],
    "verb": [
      "warn"
    ],
    "location": [
      "Esfahan Province"
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Amir Sadeghi",
    "adj": [
      "LIFE Magazine photographer"
    ],
    "verb": [
      "warn"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Maziar Bahari",
    "adj": [
      "Canadian citizen",
      "Iranian-born",
      "Newsweek journalist"
    ],
    "verb": [
      "warn"
    ],
    "location": [
      "Evin Prison"
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "General Ali Fazli",
    "adj": [
      "newly appointed commander"
    ],
    "verb": [
      "been arrest"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Los Angeles Times",
    "adj": [
    ],
    "verb": [
      "report"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Ali Larijani",
    "adj": [
      "Iran's parliament speaker"
    ],
    "verb": [
      "deny"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Ismail Ahmadi Moghaddam",
    "adj": [
      "Iran's police chief"
    ],
    "verb": [
      "acknowledge"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Reza Allamehzadeh",
    "adj": [
      "Iranian film maker"
    ],
    "verb": [
      "made"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Azar Al-Kanan",
    "adj": [
      "prominent Iranian human rights activist",
      "former political prisoner"
    ],
    "verb": [
      "become"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Fereshteh Ghazi",
    "adj": [
    ],
    "verb": [
      "write",
      "describe"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Al Jazeera English",
    "adj": [
    ],
    "verb": [
      "reveal"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Jef Lambrecht",
    "adj": [
      "Belgian national television reporter"
    ],
    "verb": [
      "been arrest",
      "go"
    ],
    "location": [
      "Tehran"
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "IRGC",
    "adj": [
    ],
    "verb": [
      "have"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  }
]

=== pegahsafaie/GraphGenerator/src/main/webapp/ground/ground_profiles_Socrates.json
[
  {
    "name": "Socrates",
    "adj": [
      "central figure",
      "pupil",
      "favorite",
      "attracted",
      "not able",
      "young man",
      "main character",
      "witty",
      "stock character",
      "President of the Athenian Senate",
      "influential"
    ],
    "verb": [
      "left",
      "become",
      "give up",
      "credit",
      "claime",
      "state",
      "seem",
      "live",
      "reply",
      "move",
      "attend",
      "go",
      "charge",
      "turn down",
      "explain",
      "decide",
      "find",
      "go",
      "discover",
      "spend",
      "separate",
      "believe",
      "go",
      "fight",
      "serve",
      "rescue",
      "have",
      "oppose",
      "choose",
      "avoid",
      "refuse",
      "argue",
      "stay",
      "call",
      "criticize",
      "continue",
      "create",
      "annoy",
      "suffer",
      "prevent",
      "wrong",
      "give",
      "choose",
      "suggest",
      "rule out",
      "offer"
    ],
    "location": [
      "Athens",
      "Athenian military",
      "Agora",
      "Potidaea",
      "Amphipolis",
      "Delium"
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Sophroniscus",
    "adj": [
      "sculptor",
      "stone-mason"
    ],
    "verb": [
    ],
    "location": [
      ""
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Phaenarete",
    "adj": [
      "midwife"
    ],
    "verb": [
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Crito",
    "adj": [
      "wealthy Athenian"
    ],
    "verb": [
      "take",
      "pay"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Anaxagoras",
    "adj": [
    ],
    "verb": [
    ],
    "location": [
      "Athens"
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Archelaus",
    "adj": [
      "physicist"
    ],
    "verb": [
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Aspasia",
    "adj": [
      "author"
    ],
    "verb": [
      "teach"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Diotima of Mantineia",
    "adj": [
    ],
    "verb": [
      "instruct"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Xanthippe",
    "adj": [
      "wife",
      "best know",
      "younger",
      "overwhelmed"
    ],
    "verb": [
      "share",
      "sit",
      "become"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Chaerephon",
    "adj": [
      "leader of the democratic party"
    ],
    "verb": [
      "go"
    ],
    "location": [
      "Athens",
      "Delphic oracle"
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Aristophanes",
    "adj": [
    ],
    "verb": [
      "know"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Xenophon",
    "adj": [
      "successful military man"
    ],
    "verb": [
      "see",
      "write"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Plato",
    "adj": [
      "brilliant writer",
      "original writer",
      "great philosopher"
    ],
    "verb": [
      "take",
      "turn"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Aristotle",
    "adj": [
      "most famous student"
    ],
    "verb": [
      "meet",
      "say"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "positive"
  },
  {
    "name": "Alcibiades",
    "adj": [
      "wounded pupil",
      "egotistical",
      "unstable",
      "favorite student",
      "Brilliant",
      "handsome",
      "rich"
    ],
    "verb": [
      "convince",
      "reach",
      "fled",
      "reveal",
      "further",
      "hope",
      "seduce",
      "loose"
    ],
    "location": [
      "Italy",
      "Athens",
      "Persia",
      "Turkey"
    ],
    "personality": "",
    "sentiment": "negative"
  },
  {
    "name": "Critias",
    "adj": [
    ],
    "verb": [
      "convince",
      "order",
      "live",
      "murder",
      "think",
      "call"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "very negative"
  },
  {
    "name": "Charmides",
    "adj": [
    ],
    "verb": [
      "live",
      "murder",
      "call"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": "negative"
  }
]

=== pegahsafaie/GraphGenerator/src/main/webapp/ground/ground_profiles_SampleInterview.json
[
  {
    "name": "Trump",
    "adj": [
      "president",
      "Mr"
    ],
    "verb": [
      "speak",
      "fulfill",
      "shake"
    ],
    "location": [
      "Oval Office",
      "Crimea",
      "Eiffel Tower",
      "Paris",
      "France",
      "Poland",
      "Britain"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Peter Baker",
    "adj": [
      "reporter"
    ],
    "verb": [
    ],
    "location": [
      "Oval Office"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Michael S. Schmidt",
    "adj": [
      "reporter"
    ],
    "verb": [
    ],
    "location": [
      "Oval Office"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Maggie Haberman",
    "adj": [
      "reporter"
    ],
    "verb": [
    ],
    "location": [
      "Oval Office"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Hope Hicks",
    "adj": [
      "White House spokeswoman"
    ],
    "verb": [
    ],
    "location": [

    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Ivanka Trump",
    "adj": [
      "advisor",
      "amazing",
      "great"
    ],
    "verb": [
      "speak"
    ],
    "location": [
      "Chinese"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Arabella",
    "adj": [
      "unbelievable","granddaughter"
    ],
    "verb": [
      "enter"
    ],
    "location": [
      "Chinese"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Hillary Clinton",
    "adj": [
      "first lady",
      "secretary"
    ],
    "verb": [
      "work",
      "get",
      "go",
      "dye",
      "oppose"
    ],
    "location": [
      "White House",
      "Russia"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Obama",
    "adj": [
    ],
    "verb": [
      "work",
      "get",
      "give",
      "allow",
      "talk"
    ],
    "location": [
      "Crimea",
      "North Korea"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "McCain",
    "adj": [
      "Senator"
    ],
    "verb": [
      "be"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Mr. Macron",
    "adj": [

    ],
    "verb": [
      "invite",
      "ask"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Angela Merkel",
    "adj": [
      "Chancellor"
    ],
    "verb": [
      "call",
      "say"
    ],
    "location": [
      "Germany"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Napoleon",
    "adj": [
    ],
    "verb": [
      "finish",
      "design"
    ],
    "location": [
      "Paris",
      "Russia"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Hitler",
    "adj": [
    ],
    "verb": [
      "want"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Harry Truman",
    "adj": [
      "first"
    ],
    "verb": [
      "beat"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Putin",
    "adj": [
      "president"
    ],
    "verb": [
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Glenn Thrush",
    "adj": [
    ],
    "verb": [
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Abe",
    "adj": [
      "Prime Minister"
    ],
    "verb": [
      "speak"
    ],
    "location": [
      "Japan"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Melania",
    "adj": [
    ],
    "verb": [
      "sit",
      "speak"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Don",
    "adj": [
    ],
    "verb": [
      "have"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Mattis",
    "adj": [
      "Defense Secretary",
      "General"
    ],
    "verb": [
      "have"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "James B. Comey",
    "adj": [
    ],
    "verb": [
      "bring",
      "share",
      "show",
      "write"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "F.B.I.",
    "adj": [
    ],
    "verb": [
      "start"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Mueller",
    "adj": [
      "special counsel"
    ],
    "verb": [
      "go"
    ],
    "location": [
      "Russia"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Jeff",
    "adj": [
      "Attorney General"
    ],
    "verb": [
      "know"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Rosenstein",
    "adj": [
    ],
    "verb": [
      "leave",
      "become",
      "give"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Flynn",
    "adj": [
    ],
    "verb": [
      "leave",
      "become",
      "give"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Richard Nixon",
    "adj": [
    ],
    "verb": [
      "come"
    ],
    "location": [
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "Xi",
    "adj": [
      "president"
    ],
    "verb": [
    ],
    "location": [
      "China"
    ],
    "personality": "",
    "sentiment": ""
  },
  {
    "name": "McCabe",
    "adj": [
      "president"
    ],
    "verb": [
    ],
    "location": [
      "Russia"
    ],
    "personality": "",
    "sentiment": ""
  }
]
